from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.changan.lib import (
    Fill,
    Materials as M,
    add_fill,
    run_builder,
)


"""
Roof ornament details for Tang-style buildings:
- Chiwei (鸱吻) at roof ridge ends
- Ridge beasts along main ridge
- Eave tile fringe using slabs
- Pagoda finials

Targets are described as (name, ridge_x1, ridge_z1, ridge_x2, ridge_z2, ridge_y).
For a north-south ridge x1==x2; for an east-west ridge z1==z2.
"""


def add_chiwen(fills: list[Fill], name: str, x: int, y: int, z: int, facing: str) -> None:
    """Add a chiwei (ridge-end guardian beast)."""
    if facing in ("n", "s"):
        add_fill(fills, f"{name} chiwen body", (x - 3, y, z - 2), (x + 3, y + 6, z + 2), M.GOLD)
        add_fill(fills, f"{name} chiwen head", (x - 2, y + 4, z - 4), (x + 2, y + 8, z - 1), M.GOLD)
        add_fill(fills, f"{name} chiwen tail", (x - 2, y + 2, z + 1), (x + 2, y + 5, z + 5), M.GOLD)
    else:
        add_fill(fills, f"{name} chiwen body", (x - 2, y, z - 3), (x + 2, y + 6, z + 3), M.GOLD)
        add_fill(fills, f"{name} chiwen head", (x - 4, y + 4, z - 2), (x - 1, y + 8, z + 2), M.GOLD)
        add_fill(fills, f"{name} chiwen tail", (x + 1, y + 2, z - 2), (x + 5, y + 5, z + 2), M.GOLD)


def add_ridge_beasts(fills: list[Fill], name: str, x1: int, z1: int, x2: int, z2: int, y: int) -> None:
    """Add small golden beasts along the central ridge."""
    if x1 == x2:
        # Ridge runs north-south
        for z in range(min(z1, z2) + 20, max(z1, z2) - 15, 30):
            add_fill(fills, f"{name} beast {z}", (x1 - 1, y, z - 1), (x1 + 1, y + 2, z + 1), M.GOLD)
    else:
        for x in range(min(x1, x2) + 20, max(x1, x2) - 15, 30):
            add_fill(fills, f"{name} beast {x}", (x - 1, y, z1 - 1), (x + 1, y + 2, z1 + 1), M.GOLD)


def add_eave_tiles(fills: list[Fill], name: str, x1: int, z1: int, x2: int, z2: int, y: int) -> None:
    """Add a fringe of alternating roof tiles along the eave edge."""
    if abs(x2 - x1) > abs(z2 - z1):
        # Long edge along x
        for x in range(min(x1, x2) + 2, max(x1, x2) - 1, 4):
            add_fill(fills, f"{name} eave tile {x}", (x, y, z1), (x + 1, y, z1 + 1), M.ROOF_GREEN_SLAB if x % 8 == 0 else M.ROOF_BLUE_SLAB)
            add_fill(fills, f"{name} eave tile s {x}", (x, y, z2 - 1), (x + 1, y, z2), M.ROOF_GREEN_SLAB if x % 8 == 0 else M.ROOF_BLUE_SLAB)
    else:
        for z in range(min(z1, z2) + 2, max(z1, z2) - 1, 4):
            add_fill(fills, f"{name} eave tile {z}", (x1, y, z), (x1 + 1, y, z + 1), M.ROOF_GREEN_SLAB if z % 8 == 0 else M.ROOF_BLUE_SLAB)
            add_fill(fills, f"{name} eave tile e {z}", (x2 - 1, y, z), (x2, y, z + 1), M.ROOF_GREEN_SLAB if z % 8 == 0 else M.ROOF_BLUE_SLAB)


def add_roof_ornament_set(
    fills: list[Fill],
    name: str,
    x1: int,
    z1: int,
    x2: int,
    z2: int,
    y: int,
) -> None:
    """Add ridge beasts, chiwei, and eave tiles for one roof ridge."""
    add_ridge_beasts(fills, name, x1, z1, x2, z2, y)
    if x1 == x2:
        # North-south ridge: chiwei at north and south ends
        add_chiwen(fills, name + " n", x1, y, min(z1, z2) + 4, "n")
        add_chiwen(fills, name + " s", x1, y, max(z1, z2) - 4, "s")
    else:
        # East-west ridge: chiwei at west and east ends
        add_chiwen(fills, name + " w", min(x1, x2) + 4, y, z1, "w")
        add_chiwen(fills, name + " e", max(x1, x2) - 4, y, z1, "e")
    add_eave_tiles(fills, name, x1 - 4, z1 - 4, x2 + 4, z2 + 4, y - 1)


# (name, ridge_x1, ridge_z1, ridge_x2, ridge_z2, ridge_y)
# Coordinates match the roofs generated by the palace/temple/gate modules.
ROOF_TARGETS: list[tuple[str, int, int, int, int, int]] = [
    # Daming Palace main halls
    ("hanyuan", 3000, 5148, 3000, 5512, 73),
    ("xuanzheng", 3000, 4860, 3000, 5100, 56),
    ("zichen", 2490, 5186, 2490, 5494, 43),
    # Daming Palace gates and pavilions
    ("danfeng", 3000, 4046, 3000, 4154, 69),
    ("daming_que_w", 2850, 4064, 2850, 4136, 57),
    ("daming_que_e", 3150, 4064, 3150, 4136, 57),
    ("penglai", 3000, 5594, 3000, 5646, 35),
    # Taiji Palace
    ("taiji_chengtian", 3000, 4714, 3000, 4726, 27),
    ("taiji_hall", 3000, 5034, 3000, 5166, 56),
    ("taiji_liangyi", 3000, 5356, 3000, 5444, 43),
    ("taiji_office_w", 2340, 4898, 2340, 5702, 27),
    ("taiji_office_e", 3660, 4898, 3660, 5702, 27),
    # Xingqing Palace
    ("xingqing_gate", 899, 1200, 901, 1200, 19),
    ("xingqing_flower_tower", 1020, 1450, 1020, 1510, 53),
    ("xingqing_chenxiang", 1300, 1182, 1300, 1218, 29),
    # City gates (main towers face north-south or east-west)
    ("zhuque", 3000, -46, 3000, 46, 79),
    ("mingde", 3000, -151, 3000, -29, 85),
    ("anhua", 1200, -30, 1200, 30, 63),
    ("qixia", 4800, -30, 4800, 30, 63),
    ("zhide", 1200, 5970, 1200, 6030, 63),
    ("xuanwu", 3000, 5970, 3000, 6030, 63),
    ("anli", 4800, 5970, 4800, 6030, 63),
    ("kaiyuan", -30, 1500, 30, 1500, 63),
    ("jinguang", -30, 3000, 30, 3000, 63),
    ("yanping", -30, 4500, 30, 4500, 63),
    ("tonghua", 5970, 1500, 6030, 1500, 63),
    ("chunming", 5970, 3000, 6030, 3000, 63),
    ("yanxing", 5970, 4500, 6030, 4500, 63),
    # Bell/Drum towers
    ("bell_daming", 2200, 4180, 2200, 4220, 51),
    ("drum_daming", 3800, 4180, 3800, 4220, 51),
    ("bell_taiji", 2400, 4680, 2400, 4720, 51),
    ("drum_taiji", 3600, 4680, 3600, 4720, 51),
    # Temple main halls (north-south ridges, approximate centres from module footprints)
    ("daci_mahavira", 4600, 3809, 4600, 3891, 37),
    ("daxingshan_mahavira", 1450, 2442, 1450, 2518, 39),
    ("dayan_mahavira", 1150, 3762, 1150, 3838, 39),
    ("jianfu_buddha", 1325, 3574, 1325, 3626, 27),
    ("qinglong_buddha", 5050, 1012, 5050, 1088, 37),
    ("xuandu_sanqing", 4850, 3628, 4850, 3692, 33),
    # Government / ritual
    ("shangshu_hall", 2000, 4173, 2000, 4237, 27),
    ("yushi_hall", 2200, 4373, 2200, 4437, 27),
    ("dali_hall", 2400, 4173, 2400, 4237, 27),
    ("honglu_hall", 2600, 4373, 2600, 4437, 27),
    ("taimiao_qian", 1100, 4289, 1100, 4351, 40),
    ("taimiao_zhong", 1100, 4432, 1100, 4488, 36),
    ("taimiao_hou", 1100, 4554, 1100, 4606, 32),
    ("sheji_hall", 4900, 4228, 4900, 4282, 25),
    ("academy_hall", 1900, 4398, 1900, 4482, 29),
]


# Pagoda finials (cx, cy, cz)
PAGODA_FINIALS = [
    ("giant_pagoda", 4580, 108, 3860),
    ("small_pagoda", 1320, 94, 3700),
    ("daxingshan_pagoda", 1540, 70, 2480),
    ("dayan_pagoda", 1150, 97, 3650),
    ("qinglong_pagoda", 4970, 59, 1130),
]


def build_roof_ornaments(fills: list[Fill]) -> None:
    for name, x1, z1, x2, z2, y in ROOF_TARGETS:
        add_roof_ornament_set(fills, name, x1, z1, x2, z2, y)

    for name, cx, cy, cz in PAGODA_FINIALS:
        add_fill(fills, f"{name} finial", (cx - 2, cy, cz - 2), (cx + 2, cy + 5, cz + 2), M.GOLD)


def main() -> None:
    run_builder(build_roof_ornaments, "roof_ornaments")


if __name__ == "__main__":
    main()
