from __future__ import annotations

import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "server/world/datapacks/canton_tower_led_anim/data/canton_led/function"
CX = 3400 + 48
CY = 40
CZ = 900 + 48
FRAME_COUNT = 12
TICK_INTERVAL = 20
PANEL_X = 3382
PANEL_Y = 86
PANEL_Z = 842

COLORS = [
    "red_stained_glass",
    "orange_stained_glass",
    "yellow_stained_glass",
    "lime_stained_glass",
    "cyan_stained_glass",
    "blue_stained_glass",
    "purple_stained_glass",
]
LIGHTS = ["redstone_lamp", "shroomlight", "glowstone", "sea_lantern"]
OFF_GLASS = "black_stained_glass"
OFF_LIGHT = "tinted_glass"


def twisted_radius(t: float, base: int = 32, waist: int = 10, top: int = 22, waist_t: float = 0.56) -> float:
    if t <= waist_t:
        local = t / max(0.01, waist_t)
        eased = local * local * (3 - 2 * local)
        return base + (waist - base) * eased
    local = (t - waist_t) / max(0.01, 1 - waist_t)
    eased = local * local * (3 - 2 * local)
    return waist + (top - waist) * eased


def frame_lines(frame: int) -> list[str]:
    lines = [
        f"# Canton Tower animated rainbow LED frame {frame}",
        "# Generated by scripts/generate_canton_led_animation.py",
    ]
    # Six moving spiral ribbons. Every frame rewrites the old ribbon positions
    # with a dim block and paints the new positions in rainbow colors.
    for ribbon in range(5):
        color = COLORS[(frame + ribbon * 2) % len(COLORS)]
        light = LIGHTS[(frame + ribbon) % len(LIGHTS)]
        angle_base = math.tau * ribbon / 5 + frame * math.tau / FRAME_COUNT
        old_angle_base = math.tau * ribbon / 5 + ((frame - 1) % FRAME_COUNT) * math.tau / FRAME_COUNT
        for y_local in range(64, 372, 12):
            t = (y_local - 8) / 360
            rx = twisted_radius(max(0.0, min(1.0, t)))
            rz = max(2.0, rx * 0.78)
            twist = math.radians(210) * t + y_local * 0.018
            old_angle = old_angle_base + twist
            ox = CX + round(math.cos(old_angle) * rx)
            oy = CY + y_local
            oz = CZ + round(math.sin(old_angle) * rz)
            oix = CX + round(math.cos(old_angle) * max(2.0, rx - 1.5))
            oiz = CZ + round(math.sin(old_angle) * max(2.0, rz - 1.5))
            if y_local % 24 == 0:
                lines.append(f"setblock {oix} {oy} {oiz} minecraft:{OFF_LIGHT} replace")
            lines.append(f"setblock {ox} {oy} {oz} minecraft:{OFF_GLASS} replace")

            angle = angle_base + twist
            x = CX + round(math.cos(angle) * rx)
            y = CY + y_local
            z = CZ + round(math.sin(angle) * rz)
            ix = CX + round(math.cos(angle) * max(2.0, rx - 1.5))
            iz = CZ + round(math.sin(angle) * max(2.0, rz - 1.5))
            if y_local % 24 == 0:
                lines.append(f"setblock {ix} {y} {iz} minecraft:{light} replace")
            lines.append(f"setblock {x} {y} {z} minecraft:{color} replace")
            lines.append(f"setblock {x} {y + 1} {z} minecraft:{color} replace")

    # Rotating observation deck rim highlights and upper "ribbon screen".
    for ring_y, radius in [(300, 26), (314, 24), (338, 22), (364, 19)]:
        color = COLORS[(frame + ring_y // 12) % len(COLORS)]
        light = LIGHTS[(frame + ring_y // 24) % len(LIGHTS)]
        for index in range(0, 72, 2):
            angle = math.tau * index / 72 + frame * math.tau / FRAME_COUNT
            x = CX + round(math.cos(angle) * radius)
            y = CY + ring_y
            z = CZ + round(math.sin(angle) * max(3, radius * 0.78))
            if index % 6 in (frame % 6, (frame + 1) % 6):
                lines.append(f"setblock {x} {y} {z} minecraft:{color} replace")
                lines.append(f"setblock {x} {y + 1} {z} minecraft:{light} replace")
            elif index % 6 == (frame + 3) % 6:
                lines.append(f"setblock {x} {y} {z} minecraft:blue_stained_glass replace")
                lines.append(f"setblock {x} {y + 1} {z} minecraft:{OFF_LIGHT} replace")

    # A small rotating beacon near the antenna makes the motion visible from a distance.
    for index in range(16):
        angle = math.tau * index / 16 + frame * math.tau / FRAME_COUNT
        x = CX + round(math.cos(angle) * 6)
        z = CZ + round(math.sin(angle) * 5)
        y = CY + 430 + index % 4
        if index % 4 == frame % 4:
            lines.append(f"setblock {x} {y} {z} minecraft:redstone_lamp replace")
        else:
            lines.append(f"setblock {x} {y} {z} minecraft:red_stained_glass replace")

    return lines


def control_panel_lines() -> list[str]:
    lines = [
        "# Canton Tower LED control deck",
        "# Pads from west to east: start, stop, faster, slower",
    ]
    for dx in range(13):
        for dz in range(7):
            edge = dx in (0, 12) or dz in (0, 6)
            block = "smooth_quartz" if not edge else "polished_blackstone"
            lines.append(f"setblock {PANEL_X + dx} {PANEL_Y} {PANEL_Z + dz} minecraft:{block} replace")
            if edge:
                lines.append(f"setblock {PANEL_X + dx} {PANEL_Y + 1} {PANEL_Z + dz} minecraft:black_stained_glass replace")

    pads = [
        (2, 3, "lime_concrete", "start"),
        (5, 3, "red_concrete", "stop"),
        (8, 3, "yellow_concrete", "faster"),
        (11, 3, "cyan_concrete", "slower"),
    ]
    for dx, dz, block, name in pads:
        x = PANEL_X + dx
        z = PANEL_Z + dz
        lines.append(f"setblock {x} {PANEL_Y + 1} {z} minecraft:{block} replace")
        lines.append(f"setblock {x} {PANEL_Y + 2} {z} minecraft:stone_pressure_plate replace")
        lines.append(f"setblock {x} {PANEL_Y + 3} {z} minecraft:sea_lantern replace")
        lines.append(f"# {name}: {x} {PANEL_Y + 2} {z}")

    for dx in range(1, 12):
        if dx not in (2, 5, 8, 11):
            lines.append(f"setblock {PANEL_X + dx} {PANEL_Y + 1} {PANEL_Z + 3} minecraft:gray_concrete replace")

    return lines


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for frame in range(FRAME_COUNT):
        (OUT / f"frame{frame}.mcfunction").write_text("\n".join(frame_lines(frame)) + "\n", encoding="utf-8")
    (OUT / "control_panel.mcfunction").write_text(
        "\n".join(control_panel_lines()) + "\n",
        encoding="utf-8",
    )
    (OUT / "load.mcfunction").write_text(
        "\n".join(
            [
                "scoreboard objectives add canton_led_tick dummy",
                "scoreboard objectives add canton_led_frame dummy",
                "scoreboard objectives add canton_led_control dummy",
                "scoreboard players set #t canton_led_tick 0",
                "scoreboard players set #f canton_led_frame 0",
                "scoreboard players set #on canton_led_frame 0",
                f"scoreboard players set #speed canton_led_tick {TICK_INTERVAL}",
                "scoreboard players set #cd canton_led_control 0",
                "function canton_led:control_panel",
                "function canton_led:frame0",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    (OUT / "tick.mcfunction").write_text(
        "\n".join(
            [
                "execute if score #on canton_led_frame matches 1 run scoreboard players add #t canton_led_tick 1",
                "execute if score #on canton_led_frame matches 1 if score #t canton_led_tick >= #speed canton_led_tick run function canton_led:advance",
                "function canton_led:control",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    advance = [
        "scoreboard players set #t canton_led_tick 0",
        "scoreboard players add #f canton_led_frame 1",
        f"execute if score #f canton_led_frame matches {FRAME_COUNT}.. run scoreboard players set #f canton_led_frame 0",
    ]
    advance.extend(
        f"execute if score #f canton_led_frame matches {frame} run function canton_led:frame{frame}"
        for frame in range(FRAME_COUNT)
    )
    (OUT / "advance.mcfunction").write_text("\n".join(advance) + "\n", encoding="utf-8")
    (OUT / "start.mcfunction").write_text(
        "scoreboard players set #on canton_led_frame 1\n",
        encoding="utf-8",
    )
    (OUT / "stop.mcfunction").write_text(
        "scoreboard players set #on canton_led_frame 0\n",
        encoding="utf-8",
    )
    (OUT / "static.mcfunction").write_text(
        "\n".join(
            [
                "scoreboard players set #on canton_led_frame 0",
                "function canton_led:frame0",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    (OUT / "faster.mcfunction").write_text(
        "\n".join(
            [
                "scoreboard players remove #speed canton_led_tick 1",
                "execute if score #speed canton_led_tick matches ..3 run scoreboard players set #speed canton_led_tick 3",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    (OUT / "slower.mcfunction").write_text(
        "\n".join(
            [
                "scoreboard players add #speed canton_led_tick 1",
                "execute if score #speed canton_led_tick matches 31.. run scoreboard players set #speed canton_led_tick 30",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    control = [
        "scoreboard players remove #cd canton_led_control 1",
        "execute if score #cd canton_led_control matches ..-1 run scoreboard players set #cd canton_led_control 0",
        f"execute if score #cd canton_led_control matches 0 if entity @a[x={PANEL_X + 2},y={PANEL_Y + 1},z={PANEL_Z + 3},dx=0,dy=4,dz=0] run function canton_led:trigger_start",
        f"execute if score #cd canton_led_control matches 0 if entity @a[x={PANEL_X + 5},y={PANEL_Y + 1},z={PANEL_Z + 3},dx=0,dy=4,dz=0] run function canton_led:trigger_stop",
        f"execute if score #cd canton_led_control matches 0 if entity @a[x={PANEL_X + 8},y={PANEL_Y + 1},z={PANEL_Z + 3},dx=0,dy=4,dz=0] run function canton_led:trigger_faster",
        f"execute if score #cd canton_led_control matches 0 if entity @a[x={PANEL_X + 11},y={PANEL_Y + 1},z={PANEL_Z + 3},dx=0,dy=4,dz=0] run function canton_led:trigger_slower",
    ]
    (OUT / "control.mcfunction").write_text("\n".join(control) + "\n", encoding="utf-8")
    triggers = {
        "start": ["function canton_led:start", 'tellraw @a {"text":"Canton Tower LED animation: START","color":"green"}'],
        "stop": ["function canton_led:stop", 'tellraw @a {"text":"Canton Tower LED animation: STOP","color":"red"}'],
        "faster": ["function canton_led:faster", 'tellraw @a {"text":"Canton Tower LED animation: FASTER","color":"yellow"}'],
        "slower": ["function canton_led:slower", 'tellraw @a {"text":"Canton Tower LED animation: SLOWER","color":"aqua"}'],
    }
    for name, body in triggers.items():
        (OUT / f"trigger_{name}.mcfunction").write_text(
            "\n".join([*body, "scoreboard players set #cd canton_led_control 20"]) + "\n",
            encoding="utf-8",
        )
    print(f"wrote animation frames to {OUT}")


if __name__ == "__main__":
    main()
